### PR TITLE
feat(nos): fallback

### PR DESCRIPTION
**Pull request by jeroenptrs**

### CODE REVIEW

**Comment by DalderupMaurice** [comment]
Wouldn't it make more sense to create an option (`nos.setFallback)` and pass a function to it, instead of passing a function to every other class? 😄

**Comment by jeroenptrs** [comment]
@DalderupMaurice Yes and no. No because a general `setFallback` is out of the option, so you would be providing a fallback (or fallback object) for every nos function. 

Yes because that fallback option can then easily be reused in every function. Especially if we can do something like this:
```javascript
const nos = window.NOS && window.NOS.V1 ? window.NOS.V1 : {};
const exists = !!window.NOS && !!window.NOS.V1;
const fallback = fallback => ({ ...fallback });

const nosFunctions = {
  exists,
  getAddress: () => exists ? nos.getAddress() : fallback.getAddress(),
  // Rest of the functions
}
```

**Comment by DalderupMaurice** [comment]
Yeah looks good! If you can be sure that the fallback does contain getAddress etc :P

**Comment by jeroenptrs** [comment]
Also I forgot to split the fallback object and setting the fallback, this would have to be done something like this:
```javascript
const fallback = {};
const setFallback = fb => {
  Object.keys(fb).forEach(func => {
    fallback[func] = fb[func];
 });
};
```

**Comment by DalderupMaurice** [comment]
What's the status of this?

**Comment by jeroenptrs** [comment]
@DalderupMaurice unnecessary, closing now

**Pull request closed without merging**
